// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SchedularService.proto

package SchedularService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplyRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=Vendor,proto3" json:"Vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=Brand,proto3" json:"Brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{0}
}

func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (m *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(m, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *ApplyRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type UserScheduleResponse struct {
	LauncherPage         []*LauncherPage `protobuf:"bytes,1,rep,name=LauncherPage,proto3" json:"LauncherPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserScheduleResponse) Reset()         { *m = UserScheduleResponse{} }
func (m *UserScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*UserScheduleResponse) ProtoMessage()    {}
func (*UserScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{1}
}

func (m *UserScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScheduleResponse.Unmarshal(m, b)
}
func (m *UserScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScheduleResponse.Marshal(b, m, deterministic)
}
func (m *UserScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScheduleResponse.Merge(m, src)
}
func (m *UserScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_UserScheduleResponse.Size(m)
}
func (m *UserScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserScheduleResponse proto.InternalMessageInfo

func (m *UserScheduleResponse) GetLauncherPage() []*LauncherPage {
	if m != nil {
		return m.LauncherPage
	}
	return nil
}

type LauncherPage struct {
	PageName             string          `protobuf:"bytes,1,opt,name=PageName,proto3" json:"PageName,omitempty"`
	Carousel             []*Carousel     `protobuf:"bytes,2,rep,name=Carousel,proto3" json:"Carousel,omitempty"`
	LauncherRows         []*LauncherRows `protobuf:"bytes,3,rep,name=LauncherRows,proto3" json:"LauncherRows,omitempty"`
	PageIndex            int32           `protobuf:"varint,4,opt,name=PageIndex,proto3" json:"PageIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LauncherPage) Reset()         { *m = LauncherPage{} }
func (m *LauncherPage) String() string { return proto.CompactTextString(m) }
func (*LauncherPage) ProtoMessage()    {}
func (*LauncherPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{2}
}

func (m *LauncherPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LauncherPage.Unmarshal(m, b)
}
func (m *LauncherPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LauncherPage.Marshal(b, m, deterministic)
}
func (m *LauncherPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LauncherPage.Merge(m, src)
}
func (m *LauncherPage) XXX_Size() int {
	return xxx_messageInfo_LauncherPage.Size(m)
}
func (m *LauncherPage) XXX_DiscardUnknown() {
	xxx_messageInfo_LauncherPage.DiscardUnknown(m)
}

var xxx_messageInfo_LauncherPage proto.InternalMessageInfo

func (m *LauncherPage) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *LauncherPage) GetCarousel() []*Carousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *LauncherPage) GetLauncherRows() []*LauncherRows {
	if m != nil {
		return m.LauncherRows
	}
	return nil
}

func (m *LauncherPage) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

type LauncherRows struct {
	RowName              string   `protobuf:"bytes,1,opt,name=RowName,proto3" json:"RowName,omitempty"`
	RowId                string   `protobuf:"bytes,2,opt,name=RowId,proto3" json:"RowId,omitempty"`
	RowIndex             int32    `protobuf:"varint,3,opt,name=RowIndex,proto3" json:"RowIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LauncherRows) Reset()         { *m = LauncherRows{} }
func (m *LauncherRows) String() string { return proto.CompactTextString(m) }
func (*LauncherRows) ProtoMessage()    {}
func (*LauncherRows) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{3}
}

func (m *LauncherRows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LauncherRows.Unmarshal(m, b)
}
func (m *LauncherRows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LauncherRows.Marshal(b, m, deterministic)
}
func (m *LauncherRows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LauncherRows.Merge(m, src)
}
func (m *LauncherRows) XXX_Size() int {
	return xxx_messageInfo_LauncherRows.Size(m)
}
func (m *LauncherRows) XXX_DiscardUnknown() {
	xxx_messageInfo_LauncherRows.DiscardUnknown(m)
}

var xxx_messageInfo_LauncherRows proto.InternalMessageInfo

func (m *LauncherRows) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *LauncherRows) GetRowId() string {
	if m != nil {
		return m.RowId
	}
	return ""
}

func (m *LauncherRows) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

type ServiceResponse struct {
	IsSuccessfull        bool     `protobuf:"varint,1,opt,name=IsSuccessfull,proto3" json:"IsSuccessfull,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceResponse) Reset()         { *m = ServiceResponse{} }
func (m *ServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceResponse) ProtoMessage()    {}
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{4}
}

func (m *ServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceResponse.Unmarshal(m, b)
}
func (m *ServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceResponse.Marshal(b, m, deterministic)
}
func (m *ServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceResponse.Merge(m, src)
}
func (m *ServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceResponse.Size(m)
}
func (m *ServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceResponse proto.InternalMessageInfo

func (m *ServiceResponse) GetIsSuccessfull() bool {
	if m != nil {
		return m.IsSuccessfull
	}
	return false
}

func (m *ServiceResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RequestSchedule struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=Vendor,proto3" json:"Vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=Brand,proto3" json:"Brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSchedule) Reset()         { *m = RequestSchedule{} }
func (m *RequestSchedule) String() string { return proto.CompactTextString(m) }
func (*RequestSchedule) ProtoMessage()    {}
func (*RequestSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{5}
}

func (m *RequestSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSchedule.Unmarshal(m, b)
}
func (m *RequestSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSchedule.Marshal(b, m, deterministic)
}
func (m *RequestSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSchedule.Merge(m, src)
}
func (m *RequestSchedule) XXX_Size() int {
	return xxx_messageInfo_RequestSchedule.Size(m)
}
func (m *RequestSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSchedule proto.InternalMessageInfo

func (m *RequestSchedule) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *RequestSchedule) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type CloudwalkerScheduler struct {
	Vendor               string      `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string      `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Shedule              []*Schedule `protobuf:"bytes,3,rep,name=shedule,proto3" json:"shedule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CloudwalkerScheduler) Reset()         { *m = CloudwalkerScheduler{} }
func (m *CloudwalkerScheduler) String() string { return proto.CompactTextString(m) }
func (*CloudwalkerScheduler) ProtoMessage()    {}
func (*CloudwalkerScheduler) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{6}
}

func (m *CloudwalkerScheduler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudwalkerScheduler.Unmarshal(m, b)
}
func (m *CloudwalkerScheduler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudwalkerScheduler.Marshal(b, m, deterministic)
}
func (m *CloudwalkerScheduler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudwalkerScheduler.Merge(m, src)
}
func (m *CloudwalkerScheduler) XXX_Size() int {
	return xxx_messageInfo_CloudwalkerScheduler.Size(m)
}
func (m *CloudwalkerScheduler) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudwalkerScheduler.DiscardUnknown(m)
}

var xxx_messageInfo_CloudwalkerScheduler proto.InternalMessageInfo

func (m *CloudwalkerScheduler) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *CloudwalkerScheduler) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *CloudwalkerScheduler) GetShedule() []*Schedule {
	if m != nil {
		return m.Shedule
	}
	return nil
}

type Schedule struct {
	TimeZone             string   `protobuf:"bytes,1,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	Pages                []*Pages `protobuf:"bytes,2,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{7}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *Schedule) GetPages() []*Pages {
	if m != nil {
		return m.Pages
	}
	return nil
}

type Pages struct {
	PageName             string      `protobuf:"bytes,1,opt,name=pageName,proto3" json:"pageName,omitempty"`
	PageIndex            int32       `protobuf:"varint,2,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	Carousel             []*Carousel `protobuf:"bytes,3,rep,name=carousel,proto3" json:"carousel,omitempty"`
	Rows                 []*Rows     `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Pages) Reset()         { *m = Pages{} }
func (m *Pages) String() string { return proto.CompactTextString(m) }
func (*Pages) ProtoMessage()    {}
func (*Pages) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{8}
}

func (m *Pages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pages.Unmarshal(m, b)
}
func (m *Pages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pages.Marshal(b, m, deterministic)
}
func (m *Pages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pages.Merge(m, src)
}
func (m *Pages) XXX_Size() int {
	return xxx_messageInfo_Pages.Size(m)
}
func (m *Pages) XXX_DiscardUnknown() {
	xxx_messageInfo_Pages.DiscardUnknown(m)
}

var xxx_messageInfo_Pages proto.InternalMessageInfo

func (m *Pages) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *Pages) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *Pages) GetCarousel() []*Carousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *Pages) GetRows() []*Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Carousel struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Carousel) Reset()         { *m = Carousel{} }
func (m *Carousel) String() string { return proto.CompactTextString(m) }
func (*Carousel) ProtoMessage()    {}
func (*Carousel) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{9}
}

func (m *Carousel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carousel.Unmarshal(m, b)
}
func (m *Carousel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carousel.Marshal(b, m, deterministic)
}
func (m *Carousel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carousel.Merge(m, src)
}
func (m *Carousel) XXX_Size() int {
	return xxx_messageInfo_Carousel.Size(m)
}
func (m *Carousel) XXX_DiscardUnknown() {
	xxx_messageInfo_Carousel.DiscardUnknown(m)
}

var xxx_messageInfo_Carousel proto.InternalMessageInfo

func (m *Carousel) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Carousel) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Carousel) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type Rows struct {
	Rowname              string   `protobuf:"bytes,1,opt,name=rowname,proto3" json:"rowname,omitempty"`
	RowIndex             int32    `protobuf:"varint,2,opt,name=rowIndex,proto3" json:"rowIndex,omitempty"`
	GenreList            []string `protobuf:"bytes,3,rep,name=genreList,proto3" json:"genreList,omitempty"`
	Languagelist         []string `protobuf:"bytes,4,rep,name=languagelist,proto3" json:"languagelist,omitempty"`
	Categorylist         []string `protobuf:"bytes,5,rep,name=categorylist,proto3" json:"categorylist,omitempty"`
	SourceList           []string `protobuf:"bytes,6,rep,name=sourceList,proto3" json:"sourceList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{10}
}

func (m *Rows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rows.Unmarshal(m, b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return xxx_messageInfo_Rows.Size(m)
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

func (m *Rows) GetRowname() string {
	if m != nil {
		return m.Rowname
	}
	return ""
}

func (m *Rows) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

func (m *Rows) GetGenreList() []string {
	if m != nil {
		return m.GenreList
	}
	return nil
}

func (m *Rows) GetLanguagelist() []string {
	if m != nil {
		return m.Languagelist
	}
	return nil
}

func (m *Rows) GetCategorylist() []string {
	if m != nil {
		return m.Categorylist
	}
	return nil
}

func (m *Rows) GetSourceList() []string {
	if m != nil {
		return m.SourceList
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplyRequest)(nil), "SchedularService.ApplyRequest")
	proto.RegisterType((*UserScheduleResponse)(nil), "SchedularService.UserScheduleResponse")
	proto.RegisterType((*LauncherPage)(nil), "SchedularService.LauncherPage")
	proto.RegisterType((*LauncherRows)(nil), "SchedularService.LauncherRows")
	proto.RegisterType((*ServiceResponse)(nil), "SchedularService.ServiceResponse")
	proto.RegisterType((*RequestSchedule)(nil), "SchedularService.RequestSchedule")
	proto.RegisterType((*CloudwalkerScheduler)(nil), "SchedularService.CloudwalkerScheduler")
	proto.RegisterType((*Schedule)(nil), "SchedularService.Schedule")
	proto.RegisterType((*Pages)(nil), "SchedularService.Pages")
	proto.RegisterType((*Carousel)(nil), "SchedularService.Carousel")
	proto.RegisterType((*Rows)(nil), "SchedularService.Rows")
}

func init() { proto.RegisterFile("SchedularService.proto", fileDescriptor_199c4d2fc282de6a) }

var fileDescriptor_199c4d2fc282de6a = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6a, 0x13, 0x41,
	0x18, 0x65, 0x9b, 0x9f, 0x26, 0x5f, 0x23, 0x95, 0x21, 0xc4, 0x25, 0x48, 0x89, 0x83, 0x48, 0x10,
	0xec, 0x45, 0x15, 0xaf, 0x04, 0xb1, 0xbd, 0x90, 0x40, 0x15, 0x9d, 0x90, 0xa2, 0xb9, 0x9b, 0x6e,
	0x3e, 0xb7, 0xa1, 0x9b, 0x9d, 0x75, 0x66, 0x37, 0xb1, 0xbe, 0x8f, 0x2f, 0x22, 0x82, 0xaf, 0x25,
	0x33, 0xbb, 0x33, 0xd9, 0x4d, 0x16, 0x8a, 0x57, 0xc9, 0x39, 0x9c, 0xef, 0xff, 0xcc, 0xc2, 0x60,
	0x1a, 0xdc, 0xe0, 0x22, 0x8b, 0xb8, 0x9c, 0xa2, 0x5c, 0x2f, 0x03, 0x3c, 0x4d, 0xa4, 0x48, 0x05,
	0x79, 0xb8, 0xcb, 0xd3, 0x37, 0xd0, 0x7b, 0x97, 0x24, 0xd1, 0x1d, 0xc3, 0xef, 0x19, 0xaa, 0x94,
	0x0c, 0xa0, 0x7d, 0x85, 0xf1, 0x42, 0x48, 0xdf, 0x1b, 0x79, 0xe3, 0x2e, 0x2b, 0x10, 0xe9, 0x43,
	0xeb, 0x5c, 0xf2, 0x78, 0xe1, 0x1f, 0x18, 0x3a, 0x07, 0x74, 0x0e, 0xfd, 0x99, 0x42, 0x59, 0x64,
	0x45, 0x86, 0x2a, 0x11, 0xb1, 0x42, 0x72, 0x0e, 0xbd, 0x4b, 0x9e, 0xc5, 0xc1, 0x0d, 0xca, 0x4f,
	0x3c, 0x44, 0xdf, 0x1b, 0x35, 0xc6, 0x47, 0x67, 0x27, 0xa7, 0x7b, 0x6d, 0x95, 0x55, 0xac, 0x12,
	0x43, 0xff, 0x78, 0xd5, 0x24, 0x64, 0x08, 0x1d, 0xfd, 0xfb, 0x91, 0xaf, 0xb0, 0x68, 0xce, 0x61,
	0xf2, 0x1a, 0x3a, 0x17, 0x5c, 0x8a, 0x4c, 0x61, 0xe4, 0x1f, 0x98, 0x62, 0xc3, 0xfd, 0x62, 0x56,
	0xc1, 0x9c, 0xb6, 0xdc, 0x28, 0x13, 0x1b, 0xe5, 0x37, 0xee, 0x6b, 0x54, 0xab, 0x58, 0x25, 0x86,
	0x3c, 0x86, 0xae, 0xee, 0x63, 0x12, 0x2f, 0xf0, 0x87, 0xdf, 0x1c, 0x79, 0xe3, 0x16, 0xdb, 0x12,
	0x74, 0x5e, 0xad, 0x40, 0x7c, 0x38, 0x64, 0x62, 0x53, 0x1a, 0xc2, 0x42, 0xbd, 0x62, 0x26, 0x36,
	0x13, 0xb7, 0x62, 0x03, 0xf4, 0xd4, 0xfa, 0x8f, 0x49, 0xde, 0x30, 0xc9, 0x1d, 0xa6, 0x9f, 0xe1,
	0xb8, 0xe8, 0xcf, 0x6d, 0xfe, 0x29, 0x3c, 0x98, 0xa8, 0x69, 0x16, 0x04, 0xa8, 0xd4, 0xb7, 0x2c,
	0x8a, 0x4c, 0x91, 0x0e, 0xab, 0x92, 0xba, 0x89, 0x15, 0x2a, 0xa5, 0x4f, 0x93, 0x17, 0xb3, 0x90,
	0xbe, 0x85, 0xe3, 0xc2, 0x0a, 0xf6, 0xa8, 0xff, 0x69, 0x89, 0x9f, 0xd0, 0xbf, 0x88, 0x44, 0xb6,
	0xd8, 0xf0, 0xe8, 0x76, 0xeb, 0x0c, 0xa9, 0xb3, 0xac, 0x2b, 0x59, 0xd6, 0x2e, 0xcb, 0x75, 0x39,
	0x8b, 0x01, 0xe4, 0x15, 0x1c, 0xaa, 0x3c, 0xb2, 0x38, 0x49, 0xcd, 0x39, 0x9d, 0xeb, 0xac, 0x94,
	0xce, 0xa0, 0xe3, 0xba, 0x1e, 0x42, 0x27, 0x5d, 0xae, 0x70, 0x2e, 0x62, 0xe7, 0x16, 0x8b, 0xc9,
	0x0b, 0x68, 0x25, 0x3c, 0x44, 0x55, 0x58, 0xe5, 0xd1, 0x7e, 0x6e, 0x7d, 0x3f, 0xc5, 0x72, 0x15,
	0xfd, 0xe5, 0x41, 0xcb, 0x10, 0x3a, 0x69, 0xb2, 0x63, 0x41, 0x8b, 0xb5, 0x0d, 0x12, 0x67, 0x83,
	0x83, 0xdc, 0x06, 0x8e, 0xd0, 0x06, 0x0d, 0xac, 0x41, 0x1b, 0xf7, 0x1b, 0xd4, 0x6a, 0xc9, 0x73,
	0x68, 0x4a, 0x6d, 0xcc, 0xa6, 0x89, 0x19, 0xec, 0xc7, 0x18, 0x43, 0x1a, 0x0d, 0xbd, 0xda, 0x3e,
	0x02, 0xbd, 0xee, 0x94, 0xcb, 0x10, 0x53, 0xbb, 0xee, 0x1c, 0x69, 0x5e, 0x89, 0x4c, 0x06, 0xf6,
	0xf0, 0x05, 0xd2, 0x93, 0x2d, 0x57, 0x3c, 0xc4, 0x99, 0x8c, 0x8c, 0xcd, 0xba, 0xcc, 0x61, 0xfa,
	0xdb, 0x83, 0xa6, 0xf5, 0xae, 0x14, 0x9b, 0xb8, 0xe4, 0xdd, 0x02, 0xea, 0x70, 0x69, 0x5d, 0x9a,
	0xcf, 0xee, 0xb0, 0x5e, 0x4c, 0x88, 0xb1, 0xc4, 0xcb, 0xa5, 0x4a, 0xcd, 0xec, 0x5d, 0xb6, 0x25,
	0x08, 0x85, 0x5e, 0xc4, 0xe3, 0x30, 0xe3, 0x21, 0x46, 0x5a, 0xd0, 0x34, 0x82, 0x0a, 0xa7, 0x35,
	0x01, 0x4f, 0x31, 0x14, 0xf2, 0xce, 0x68, 0x5a, 0xb9, 0xa6, 0xcc, 0x91, 0x13, 0x80, 0x7c, 0x14,
	0x53, 0xa6, 0x6d, 0x14, 0x25, 0xe6, 0xec, 0xaf, 0x07, 0x7b, 0x5f, 0x3f, 0xf2, 0x15, 0x7a, 0x1f,
	0xf8, 0x2d, 0x3a, 0xd3, 0x3c, 0xab, 0xb9, 0x49, 0x8d, 0x99, 0x87, 0x4f, 0x6a, 0xdc, 0xb8, 0xf3,
	0x10, 0xbf, 0xc0, 0xd1, 0x7b, 0xdc, 0x3e, 0xa2, 0x9a, 0x88, 0x9d, 0x77, 0x36, 0xac, 0x29, 0x5e,
	0xf7, 0x71, 0xbd, 0x6e, 0x9b, 0x6f, 0xf9, 0xcb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x96, 0x74,
	0x84, 0xa5, 0xe5, 0x05, 0x00, 0x00,
}
