// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SchedularService.proto

package SchedularService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplyRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=Vendor,proto3" json:"Vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=Brand,proto3" json:"Brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{0}
}

func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (m *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(m, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *ApplyRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type UserScheduleResponse struct {
	LauncherPage         []*LauncherPage `protobuf:"bytes,1,rep,name=LauncherPage,proto3" json:"LauncherPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserScheduleResponse) Reset()         { *m = UserScheduleResponse{} }
func (m *UserScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*UserScheduleResponse) ProtoMessage()    {}
func (*UserScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{1}
}

func (m *UserScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserScheduleResponse.Unmarshal(m, b)
}
func (m *UserScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserScheduleResponse.Marshal(b, m, deterministic)
}
func (m *UserScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserScheduleResponse.Merge(m, src)
}
func (m *UserScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_UserScheduleResponse.Size(m)
}
func (m *UserScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserScheduleResponse proto.InternalMessageInfo

func (m *UserScheduleResponse) GetLauncherPage() []*LauncherPage {
	if m != nil {
		return m.LauncherPage
	}
	return nil
}

type LauncherPage struct {
	PageName             string          `protobuf:"bytes,1,opt,name=PageName,proto3" json:"PageName,omitempty"`
	Carousel             []*Carousel     `protobuf:"bytes,2,rep,name=Carousel,proto3" json:"Carousel,omitempty"`
	LauncherRows         []*LauncherRows `protobuf:"bytes,3,rep,name=LauncherRows,proto3" json:"LauncherRows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LauncherPage) Reset()         { *m = LauncherPage{} }
func (m *LauncherPage) String() string { return proto.CompactTextString(m) }
func (*LauncherPage) ProtoMessage()    {}
func (*LauncherPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{2}
}

func (m *LauncherPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LauncherPage.Unmarshal(m, b)
}
func (m *LauncherPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LauncherPage.Marshal(b, m, deterministic)
}
func (m *LauncherPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LauncherPage.Merge(m, src)
}
func (m *LauncherPage) XXX_Size() int {
	return xxx_messageInfo_LauncherPage.Size(m)
}
func (m *LauncherPage) XXX_DiscardUnknown() {
	xxx_messageInfo_LauncherPage.DiscardUnknown(m)
}

var xxx_messageInfo_LauncherPage proto.InternalMessageInfo

func (m *LauncherPage) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *LauncherPage) GetCarousel() []*Carousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *LauncherPage) GetLauncherRows() []*LauncherRows {
	if m != nil {
		return m.LauncherRows
	}
	return nil
}

type LauncherRows struct {
	RowName              string   `protobuf:"bytes,1,opt,name=RowName,proto3" json:"RowName,omitempty"`
	RowId                string   `protobuf:"bytes,2,opt,name=RowId,proto3" json:"RowId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LauncherRows) Reset()         { *m = LauncherRows{} }
func (m *LauncherRows) String() string { return proto.CompactTextString(m) }
func (*LauncherRows) ProtoMessage()    {}
func (*LauncherRows) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{3}
}

func (m *LauncherRows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LauncherRows.Unmarshal(m, b)
}
func (m *LauncherRows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LauncherRows.Marshal(b, m, deterministic)
}
func (m *LauncherRows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LauncherRows.Merge(m, src)
}
func (m *LauncherRows) XXX_Size() int {
	return xxx_messageInfo_LauncherRows.Size(m)
}
func (m *LauncherRows) XXX_DiscardUnknown() {
	xxx_messageInfo_LauncherRows.DiscardUnknown(m)
}

var xxx_messageInfo_LauncherRows proto.InternalMessageInfo

func (m *LauncherRows) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *LauncherRows) GetRowId() string {
	if m != nil {
		return m.RowId
	}
	return ""
}

type ServiceResponse struct {
	IsSuccessfull        bool     `protobuf:"varint,1,opt,name=IsSuccessfull,proto3" json:"IsSuccessfull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceResponse) Reset()         { *m = ServiceResponse{} }
func (m *ServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceResponse) ProtoMessage()    {}
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{4}
}

func (m *ServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceResponse.Unmarshal(m, b)
}
func (m *ServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceResponse.Marshal(b, m, deterministic)
}
func (m *ServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceResponse.Merge(m, src)
}
func (m *ServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceResponse.Size(m)
}
func (m *ServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceResponse proto.InternalMessageInfo

func (m *ServiceResponse) GetIsSuccessfull() bool {
	if m != nil {
		return m.IsSuccessfull
	}
	return false
}

type RequestSchedule struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=Vendor,proto3" json:"Vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=Brand,proto3" json:"Brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestSchedule) Reset()         { *m = RequestSchedule{} }
func (m *RequestSchedule) String() string { return proto.CompactTextString(m) }
func (*RequestSchedule) ProtoMessage()    {}
func (*RequestSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{5}
}

func (m *RequestSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestSchedule.Unmarshal(m, b)
}
func (m *RequestSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestSchedule.Marshal(b, m, deterministic)
}
func (m *RequestSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestSchedule.Merge(m, src)
}
func (m *RequestSchedule) XXX_Size() int {
	return xxx_messageInfo_RequestSchedule.Size(m)
}
func (m *RequestSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_RequestSchedule proto.InternalMessageInfo

func (m *RequestSchedule) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *RequestSchedule) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type Schedule struct {
	TimeZone             string   `protobuf:"bytes,4,opt,name=TimeZone,proto3" json:"TimeZone,omitempty"`
	Vendor               string   `protobuf:"bytes,1,opt,name=Vendor,proto3" json:"Vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=Brand,proto3" json:"Brand,omitempty"`
	Page                 []*Page  `protobuf:"bytes,3,rep,name=Page,proto3" json:"Page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{6}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetTimeZone() string {
	if m != nil {
		return m.TimeZone
	}
	return ""
}

func (m *Schedule) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Schedule) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Schedule) GetPage() []*Page {
	if m != nil {
		return m.Page
	}
	return nil
}

type Page struct {
	PageName             string      `protobuf:"bytes,1,opt,name=PageName,proto3" json:"PageName,omitempty"`
	Carousel             []*Carousel `protobuf:"bytes,2,rep,name=Carousel,proto3" json:"Carousel,omitempty"`
	Rows                 []*Rows     `protobuf:"bytes,3,rep,name=Rows,proto3" json:"Rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{7}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *Page) GetCarousel() []*Carousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *Page) GetRows() []*Rows {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Carousel struct {
	Target               string   `protobuf:"bytes,1,opt,name=Target,proto3" json:"Target,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Carousel) Reset()         { *m = Carousel{} }
func (m *Carousel) String() string { return proto.CompactTextString(m) }
func (*Carousel) ProtoMessage()    {}
func (*Carousel) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{8}
}

func (m *Carousel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carousel.Unmarshal(m, b)
}
func (m *Carousel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carousel.Marshal(b, m, deterministic)
}
func (m *Carousel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carousel.Merge(m, src)
}
func (m *Carousel) XXX_Size() int {
	return xxx_messageInfo_Carousel.Size(m)
}
func (m *Carousel) XXX_DiscardUnknown() {
	xxx_messageInfo_Carousel.DiscardUnknown(m)
}

var xxx_messageInfo_Carousel proto.InternalMessageInfo

func (m *Carousel) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Carousel) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Carousel) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type Rows struct {
	RowName              string   `protobuf:"bytes,1,opt,name=RowName,proto3" json:"RowName,omitempty"`
	GenerList            []string `protobuf:"bytes,2,rep,name=GenerList,proto3" json:"GenerList,omitempty"`
	LanguageList         []string `protobuf:"bytes,3,rep,name=LanguageList,proto3" json:"LanguageList,omitempty"`
	CategoryList         []string `protobuf:"bytes,4,rep,name=CategoryList,proto3" json:"CategoryList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rows) Reset()         { *m = Rows{} }
func (m *Rows) String() string { return proto.CompactTextString(m) }
func (*Rows) ProtoMessage()    {}
func (*Rows) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{9}
}

func (m *Rows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rows.Unmarshal(m, b)
}
func (m *Rows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rows.Marshal(b, m, deterministic)
}
func (m *Rows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rows.Merge(m, src)
}
func (m *Rows) XXX_Size() int {
	return xxx_messageInfo_Rows.Size(m)
}
func (m *Rows) XXX_DiscardUnknown() {
	xxx_messageInfo_Rows.DiscardUnknown(m)
}

var xxx_messageInfo_Rows proto.InternalMessageInfo

func (m *Rows) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *Rows) GetGenerList() []string {
	if m != nil {
		return m.GenerList
	}
	return nil
}

func (m *Rows) GetLanguageList() []string {
	if m != nil {
		return m.LanguageList
	}
	return nil
}

func (m *Rows) GetCategoryList() []string {
	if m != nil {
		return m.CategoryList
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplyRequest)(nil), "SchedularService.ApplyRequest")
	proto.RegisterType((*UserScheduleResponse)(nil), "SchedularService.UserScheduleResponse")
	proto.RegisterType((*LauncherPage)(nil), "SchedularService.LauncherPage")
	proto.RegisterType((*LauncherRows)(nil), "SchedularService.LauncherRows")
	proto.RegisterType((*ServiceResponse)(nil), "SchedularService.ServiceResponse")
	proto.RegisterType((*RequestSchedule)(nil), "SchedularService.RequestSchedule")
	proto.RegisterType((*Schedule)(nil), "SchedularService.Schedule")
	proto.RegisterType((*Page)(nil), "SchedularService.Page")
	proto.RegisterType((*Carousel)(nil), "SchedularService.Carousel")
	proto.RegisterType((*Rows)(nil), "SchedularService.Rows")
}

func init() { proto.RegisterFile("SchedularService.proto", fileDescriptor_199c4d2fc282de6a) }

var fileDescriptor_199c4d2fc282de6a = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0x26, 0xbb, 0x6b, 0xcd, 0xbe, 0x6e, 0xa9, 0x0c, 0x65, 0x09, 0x41, 0xa4, 0x0e, 0x22, 0xa5,
	0x87, 0x1e, 0x2a, 0xe8, 0x45, 0x14, 0xdb, 0x43, 0x59, 0x68, 0x45, 0x66, 0xdb, 0x22, 0xbd, 0x8d,
	0xd9, 0x67, 0xba, 0x98, 0xcd, 0xac, 0x33, 0x89, 0x4b, 0x6f, 0x9e, 0xbc, 0xfa, 0x2f, 0xfc, 0x9d,
	0x32, 0x2f, 0x93, 0x6c, 0xb2, 0x09, 0xd4, 0x1e, 0x3c, 0x85, 0xef, 0xe5, 0x7b, 0x6f, 0xbe, 0xf7,
	0xbe, 0x37, 0x03, 0xe3, 0x69, 0x74, 0x8b, 0xb3, 0x3c, 0x91, 0x7a, 0x8a, 0xfa, 0xc7, 0x3c, 0xc2,
	0xa3, 0xa5, 0x56, 0x99, 0x62, 0x4f, 0x36, 0xe3, 0xfc, 0x2d, 0x8c, 0x3e, 0x2c, 0x97, 0xc9, 0x9d,
	0xc0, 0xef, 0x39, 0x9a, 0x8c, 0x8d, 0x61, 0xeb, 0x1a, 0xd3, 0x99, 0xd2, 0x81, 0xb7, 0xef, 0x1d,
	0x0c, 0x85, 0x43, 0x6c, 0x0f, 0x1e, 0x9d, 0x68, 0x99, 0xce, 0x82, 0x1e, 0x85, 0x0b, 0xc0, 0x6f,
	0x60, 0xef, 0xca, 0xa0, 0x76, 0x55, 0x51, 0xa0, 0x59, 0xaa, 0xd4, 0x20, 0x3b, 0x81, 0xd1, 0xb9,
	0xcc, 0xd3, 0xe8, 0x16, 0xf5, 0x27, 0x19, 0x63, 0xe0, 0xed, 0xf7, 0x0f, 0xb6, 0x8f, 0x9f, 0x1d,
	0xb5, 0x64, 0xd5, 0x59, 0xa2, 0x91, 0xc3, 0xff, 0x78, 0xcd, 0x22, 0x2c, 0x04, 0xdf, 0x7e, 0x3f,
	0xca, 0x05, 0x3a, 0x71, 0x15, 0x66, 0xaf, 0xc1, 0x3f, 0x95, 0x5a, 0xe5, 0x06, 0x93, 0xa0, 0x47,
	0x87, 0x85, 0xed, 0xc3, 0x4a, 0x86, 0xa8, 0xb8, 0x75, 0xa1, 0x42, 0xad, 0x4c, 0xd0, 0xbf, 0x4f,
	0xa8, 0x65, 0x89, 0x46, 0x0e, 0x7f, 0xd7, 0xac, 0xc1, 0x02, 0x78, 0x2c, 0xd4, 0xaa, 0x26, 0xb3,
	0x84, 0x76, 0x88, 0x42, 0xad, 0x26, 0xd5, 0x10, 0x09, 0xf0, 0x37, 0xb0, 0xeb, 0x4e, 0xa9, 0xe6,
	0xf7, 0x02, 0x76, 0x26, 0x66, 0x9a, 0x47, 0x11, 0x1a, 0xf3, 0x35, 0x4f, 0x12, 0x2a, 0xe4, 0x8b,
	0x66, 0x90, 0xbf, 0x87, 0x5d, 0x67, 0x5b, 0x69, 0xc0, 0x03, 0xed, 0xfb, 0xe9, 0x81, 0x5f, 0xa5,
	0x86, 0xe0, 0x5f, 0xce, 0x17, 0x78, 0xa3, 0x52, 0x0c, 0x06, 0xc5, 0x78, 0x4b, 0xfc, 0xb0, 0xb2,
	0xec, 0x10, 0x06, 0xe4, 0x7a, 0x31, 0xcc, 0x71, 0x7b, 0x98, 0xe4, 0x36, 0x71, 0xf8, 0x2f, 0xaf,
	0x20, 0xff, 0x17, 0x77, 0x0f, 0x61, 0x50, 0x73, 0xb5, 0x43, 0x08, 0xb9, 0x49, 0x1c, 0x7e, 0xbd,
	0x3e, 0xc3, 0xb6, 0x7b, 0x29, 0x75, 0x8c, 0x59, 0xd9, 0x6e, 0x81, 0x6c, 0x7c, 0xaa, 0x72, 0x1d,
	0xa1, 0xeb, 0xd7, 0x21, 0xab, 0x7d, 0xb2, 0x90, 0x31, 0x5e, 0xe9, 0x24, 0xe8, 0x17, 0xda, 0x4b,
	0x4c, 0x0d, 0xde, 0xb3, 0x16, 0x4f, 0x61, 0x78, 0x86, 0x29, 0xea, 0xf3, 0xb9, 0xc9, 0xa8, 0xbf,
	0xa1, 0x58, 0x07, 0x18, 0xb7, 0xeb, 0x95, 0xc6, 0xb9, 0x8c, 0x91, 0x08, 0x7d, 0x22, 0x34, 0x62,
	0x96, 0x73, 0x2a, 0x33, 0x8c, 0x95, 0xbe, 0x23, 0xce, 0xa0, 0xe0, 0xd4, 0x63, 0xc7, 0xbf, 0x7b,
	0xd0, 0xba, 0xfe, 0x4c, 0xc0, 0x0e, 0x5d, 0xff, 0x6a, 0x0b, 0x3a, 0x56, 0xbf, 0xfe, 0x3e, 0x84,
	0xcf, 0xdb, 0xff, 0x37, 0x97, 0xf7, 0x02, 0x46, 0x17, 0xf2, 0x1b, 0xae, 0x17, 0xab, 0x23, 0xc5,
	0xfd, 0xfb, 0x97, 0x72, 0x9f, 0x61, 0xfb, 0x0c, 0xd7, 0x1b, 0xde, 0x91, 0xb1, 0x71, 0x09, 0xc2,
	0x97, 0x6d, 0x4a, 0xd7, 0x2b, 0xf5, 0x65, 0x8b, 0x1e, 0xc5, 0x57, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x29, 0x69, 0x52, 0x22, 0x2e, 0x05, 0x00, 0x00,
}
